# Generated by Django 5.2.1 on 2025-05-20 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField(db_index=True, help_text='ID of the Doctor from the User Service', verbose_name='doctor id')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('is_available', models.BooleanField(default=True, help_text='Is this time slot generally available (before considering appointments)?', verbose_name='is available')),
            ],
            options={
                'verbose_name': 'doctor schedule',
                'verbose_name_plural': 'doctor schedules',
                'ordering': ['doctor_id', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(blank=True, db_index=True, help_text='ID of the Patient from the User Service', null=True, verbose_name='patient id')),
                ('doctor_id', models.IntegerField(blank=True, db_index=True, help_text='ID of the Doctor from the User Service', null=True, verbose_name='doctor id')),
                ('appointment_time', models.DateTimeField(db_index=True, verbose_name='appointment time')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='reason for appointment')),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], db_index=True, default='Scheduled', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.doctorschedule', verbose_name='schedule slot')),
            ],
            options={
                'verbose_name': 'appointment',
                'verbose_name_plural': 'appointments',
                'ordering': ['appointment_time'],
                'unique_together': {('doctor_id', 'appointment_time'), ('patient_id', 'appointment_time')},
            },
        ),
    ]
