# Generated by Django 5.2.1 on 2025-05-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_diagnosis_labtest_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='appointment',
            field=models.IntegerField(blank=True, help_text='ID of Appointment from appointment_service', null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='patient_record',
            field=models.IntegerField(blank=True, help_text='ID of PatientRecord from patient_service', null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='appointment',
            field=models.IntegerField(blank=True, help_text='ID of Appointment from appointment_service', null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='patient_record',
            field=models.IntegerField(blank=True, help_text='ID of PatientRecord from patient_service', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.IntegerField(blank=True, help_text='ID of Appointment from appointment_service', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_record',
            field=models.IntegerField(blank=True, help_text='ID of PatientRecord from patient_service', null=True),
        ),
    ]
