# Generated by Django 5.2.1 on 2025-05-21 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_diagnosis_appointment_diagnosis_patient_record_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('patient_record', models.IntegerField(blank=True, null=True)),
                ('appointment', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(max_length=255)),
                ('remind_time', models.DateTimeField()),
                ('type', models.CharField(default='general', max_length=50)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medications.medication')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medications.prescription')),
            ],
        ),
    ]
