# Generated by Django 5.2.1 on 2025-05-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_appointment_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='patient_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
