# Generated by Django 5.2.1 on 2025-05-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
